apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "account-service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "account-service.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gsaEmail | quote }}
