apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "notification-service.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels: {{- include "notification-service.selectorLabels" . | nindent 6 }}
