apiVersion: v1
kind: Service
metadata:
  name: {{ include "notification-service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "notification-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      appProtocol: http
  selector: {{- include "notification-service.selectorLabels" . | nindent 4 }}
