# ---------------------------------------------------------------------------
# Phase 5: per-service Kubernetes resources Terraform owns
#
# Terraform owns "platform" resources that need to be set up before workloads
# (namespaces, DB credentials piped from generated passwords). ArgoCD owns
# everything else (deployments, services, mesh policies).
# ---------------------------------------------------------------------------

resource "kubernetes_namespace_v1" "account_service" {
  metadata {
    name = "account-service"
    labels = {
      "istio.io/rev"                       = module.asm.control_plane_revision_label
      "pod-security.kubernetes.io/enforce" = "restricted"
      "pod-security.kubernetes.io/audit"   = "restricted"
      "pod-security.kubernetes.io/warn"    = "restricted"
    }
  }

  depends_on = [module.asm]
}

# DB password lands as a Kubernetes Secret in the service's namespace.
# Workloads consume it via envFrom; the value originates from the random
# password generated by the cloud-sql module (single source of truth).
resource "kubernetes_secret_v1" "account_service_db" {
  metadata {
    name      = "account-service-db"
    namespace = kubernetes_namespace_v1.account_service.metadata[0].name
  }

  type = "Opaque"

  data = {
    DB_USER            = "app_account"
    DB_NAME            = "accounts"
    DB_PASSWORD        = module.cloud_sql.user_passwords["app_account"]
    INSTANCE_CONNECTION_NAME = module.cloud_sql.connection_name
  }
}
