apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    istio.io/rev: asm-managed
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
